### ISSUE TITLE
Exception while generating Visualized DB diagram

### ISSUE THREAD

**Issue by tzutolin** [jGauravGupta/jpamodeler#1]
Please see the attached files.
[error.zip](https://github.com/jGauravGupta/jpamodeler/files/175121/error.zip)

**Comment by jGauravGupta** [comment]
Thanks @tzutolin for taking the time to report this bug and helping to make JPA Modeler better.
Please download the [JPA Modeler v1.5.1 ](http://plugins.netbeans.org/download/plugin/4608)

![attachscreen](https://cloud.githubusercontent.com/assets/15934072/13851558/ae317c78-ec84-11e5-9cd5-80f5b5c37967.png)

FYI, The attached file have one issue as you can view in attached file(or in v1.5.1) that it contains same name attribute more than one time. So please rename the attribute **section** .

**Comment by jGauravGupta** [comment]
@tzutolin Please confirm the status from your end and please raise issue, if any other error occurs.

Thanks very much for your support
