### ISSUE TITLE
labeling error in hashcode and equals

### ISSUE THREAD

**Issue by pembertonc** [jGauravGupta/JPAModeler#101]
The number of fields shown as used in the equals and hashcode methods appears to be swapped in the class properties.

**Comment by jGauravGupta** [comment]
Hi @pembertonc , 
Can you please share the more details.

**Comment by pembertonc** [comment]
I select two fields to be used in the hashcode method,  and one field for the equals method in the hashcode and equals dialog box. However when the editor is closed it shows hashcode{1} equals{2}.  Note this is not a show stopper.  Just mixed up labeling.

**Comment by jGauravGupta** [comment]
Thanks for reporting the issue :)

**Comment by pembertonc** [comment]
You are welcome.  and thanks for a great and useful product
