### ISSUE TITLE
Enhancement : Windows Size

### ISSUE THREAD

**Issue by neorevx** [jGauravGupta/JPAModeler#102]
Hi,

I'm here again. haha

I'm editing some snippets and I think the dialog window is too small. (It's resizable, but after close diagram, all windows come back to be a small window)
Maybe you consider enlarge the modal dialogs.

I have some code to set size of window considering OS task bar. (below)
setWindowSizeAndCenter method will set size to fit to any screen size.
The margin parameter set margin around the window. Normally, I use 50~300 px.

```
    public static void setWindowSizeAndCenter(Window window, int margin) {

        Rectangle windowableArea = getWindowableArea();
        
        int w = window.getWidth();
        int h = window.getHeight();
        
        windowableArea.width -= 2*margin;
        windowableArea.height -= 2*margin;
        
        window.setSize(Math.max(w, windowableArea.width), Math.max(h, windowableArea.height));
        
        centerWindow(window);

    }

    public static void centerWindow(Window window) {
        
        Rectangle windowableArea = getWindowableArea();

        window.setLocation(windowableArea.x + (windowableArea.width - window.getWidth()) / 2,
                windowableArea.y + (windowableArea.height - window.getHeight()) / 2);
    }
    
    public static Rectangle getWindowableArea() {
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        int width = gd.getDisplayMode().getWidth();
        int height = gd.getDisplayMode().getHeight();

        //height of the task bar
        Insets insets = Toolkit.getDefaultToolkit().getScreenInsets(gd.getDefaultConfiguration());
        
        width -= insets.left + insets.right;
        height -= insets.top + insets.bottom;
        
        return new Rectangle(insets.left, insets.top, width, height);
    }
```

**Comment by jGauravGupta** [comment]
Can you please share the screenshot or details about the window title ?

**Comment by neorevx** [comment]
I have a full hd screen (1920x1080px).
The snippet edit window default size is around 560x330px.
Look at screenshot. The window is too small for me screen size. :)
It's just a little enhancement. Not a bug. Maybe just save the last window size will work good. :D

![win](https://cloud.githubusercontent.com/assets/21008550/21186988/81f57d2c-c1fd-11e6-9f57-b8a67f3386e4.jpg)

**Comment by jGauravGupta** [comment]
Please confirm with v2.7.2.

**Comment by neorevx** [comment]
It's working for v2,7,2. Thank you. The window sizes are save by command (add, edit, ...).
But the location is not working properly.
First time I open the window, the location is not centred. Second time, is centred.
When I open a other command window (like Add afeter Edit), the Add Window is not centred too.
