### ISSUE TITLE
Erro na geração JPA

### ISSUE THREAD

**Issue by kelsenb** [jGauravGupta/JPAModeler#103]

**Comment by jGauravGupta** [comment]
Hi @kelsenb ,
Please share the stacktrace and modeler file.

**Comment by jGauravGupta** [comment]
Hi @kelsenb  ,
Please share the stacktrace to reproduce the issue.

**Comment by larslemos** [comment]
@kelsenb Em que fase de desenvolvimento o erro occoreu?
Podes compartilhar o stacktrace que aparece na consola.
