### ISSUE TITLE
How to add annotations to package-info.java ?

### ISSUE THREAD

**Issue by slavb18** [jGauravGupta/JPAModeler#104]
Hi!

How to add annotations to package-info.java ?
E.g I want to add 
@XmlJavaTypeAdapters({
    @XmlJavaTypeAdapter(type=DateTime.class, 
        value=DateTimeAdapter.class),
    @XmlJavaTypeAdapter(type=DateMidnight.class, 
        value=DateMidnightAdapter.class),
    @XmlJavaTypeAdapter(type=LocalDate.class, 
        value=LocalDateAdapter.class),
    @XmlJavaTypeAdapter(type=LocalTime.class, 
        value=LocalTimeAdapter.class),
    @XmlJavaTypeAdapter(type=LocalDateTime.class, 
        value=LocalDateTimeAdapter.class)
})

or some other custom annotations

**Comment by jGauravGupta** [comment]
package-info.java is not generated by JPA Modeler.

**Comment by slavb18** [comment]
Hi!

I have checked "JAXB Source" and filled JAXB NameSpace: qq
and see file package-info.java generated in EntityPackage:

and see in log:
Generating JAXB package-info.java
Even if I uncheck "JAXB Source", it is also generated (may be due to I have set JAXB Properties in entities, like "Root Element")

package-info.java contents:
@XmlSchema(namespace = "qq", elementFormDefault = XmlNsForm.QUALIFIED)
package ru.ilb.sampleappication.entities;

import javax.xml.bind.annotation.*;

May be there is need option to place "Snippets" before package in package-info.java.

I am new to this project and don't know where to go

**Comment by slavb18** [comment]
Found way to disable package-info.java generation - need to make  "JAXB NameSpace"
empty, now I can write it by hand, Thanks, works for me.

**Comment by jGauravGupta** [comment]
Ok, I thought, you were asking about package-info.java related to JPA/Hibernate.
