### ISSUE TITLE
Property Change Support

### ISSUE THREAD

**Issue by neorevx** [jGauravGupta/JPAModeler#106]
Hi,

I thought about some future enhancements:

**1)** Gerenate JPA Index Annotation as property of column/field. Maybe in entity selecting more then one column and the index name.

The annotation goes to entity class, like:
`@Table(indexes = { @Index(name = "IDX_MYIDX1", columnList = "id,name,surname") })`

**2)** Property Change Support. I'm using JPA for Java SE. Option to add property change support by column/field is a good thing. I think property change support should be optional by column.

Currently, Netbeans generate property change support like:
```
private String propertyNAME;

    public static final String PROP_PROPERTYNAME = "propertyNAME";

    private transient final PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    public String getPropertyNAME() {
        return propertyNAME;
    }

    public void setPropertyNAME(String propertyNAME) {
        String oldPropertyNAME = this.propertyNAME;
        this.propertyNAME = propertyNAME;
        propertyChangeSupport.firePropertyChange(PROP_PROPERTYNAME, oldPropertyNAME, propertyNAME);
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }
```

**Comment by jGauravGupta** [comment]
@Index functionality is already exist , please have a look on th attached screen-shot : 
![index](https://cloud.githubusercontent.com/assets/15934072/21460612/49353e9e-c970-11e6-9d94-3793ce87f723.PNG)

**Comment by neorevx** [comment]
Humm...

Sorry. I never saw this before. haha
It's available only in db visualizer.

I thought "Visualize DB" is only for visualization and has no properties. I'm wrong. :D

**Comment by aldranvijay** [comment]
Yes, DB Modeler is responsible for DB properties and JPA Modeler is responsible for java properties.
Even JPA Modeler has some DB properties for rescue (that will be useful to clean/delete JoinTable/JoinColum/Table properties to manually fix when DB Modeler will fail in rare complex scenario)

**Comment by neorevx** [comment]
Well, I think Property Change Support still a good thing (for future).
If you like the ideia, close this topic and make a (clean) new one. :)
If you did not like, just close haha.

Property Change Support. I'm using JPA for Java SE. Option to add property change support by column/field is a good thing. I think property change support should be optional by column.

Currently, Netbeans generate property change support like:

private String propertyNAME;

    public static final String PROP_PROPERTYNAME = "propertyNAME";

    private transient final PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    public String getPropertyNAME() {
        return propertyNAME;
    }

    public void setPropertyNAME(String propertyNAME) {
        String oldPropertyNAME = this.propertyNAME;
        this.propertyNAME = propertyNAME;
        propertyChangeSupport.firePropertyChange(PROP_PROPERTYNAME, oldPropertyNAME, propertyNAME);
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

**Comment by neorevx** [comment]
Vetoable Change Support complete Propery Change Support, but in this case, the programmer should can edit setter method for validation. Maybe snippet inside method will work.
It's just ideia. :D

**Comment by jGauravGupta** [comment]
Ticket is already raised for snippet inside method  : https://github.com/jGauravGupta/JPAModeler/issues/91

**Comment by jGauravGupta** [comment]
Hi @neorevx ,

Try to figure out this requirement with custom snippet (https://github.com/jGauravGupta/JPAModeler/issues/91) functionality and let me know :)

**Comment by neorevx** [comment]
Mostly can ben done with custom snippet. Except for vetoable change support, because throws an exception.
But it's a lot of snippets. I think the enhancement still good ideia.

I made one class with two properties so you can decide if it's worth doing this function.
Read comments please.

Ty.
```
public class PCTestClass {
    
    // Support classes, should appear one time and only if has some field with property change support
    private transient final PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);
    private transient final VetoableChangeSupport vetoableChangeSupport = new VetoableChangeSupport(this);

    // Fields
    // Three modes are possible:
    // 1 - don't not generate property change support
    // 2 - generate property change support
    // 3 - generate property and vetoable change support
    // (NB does not generate vetoable change support without property change support)
    private String property1;   // Use Property and Vetoable Change Support 
    private String property2;   // Use only Property Change Support

    // Constants for fields names, it's not necessary, can be ommited
    public static final String PROP_PROPERTY1 = "property1";
    public static final String PROP_PROPERTY2 = "property2";
    
    // *******************************************************
    // Getter and Setter for Vetoable Property Change Support
    // For VETOABLE, it's include throws PropertyVetoException
    public String getProperty1() {
        return property1;
    }

    // Code of parameter: <FieldType> <Argument1>
    public void setProperty1(String property1) throws PropertyVetoException {
        // Code: <FieldType> old<FieldName> = this.<FieldName>;
        String oldProperty1 = this.property1;
        // Code: vetoableChangeSupport.fireVetoableChange(<"FieldName" or Constant>, old<FieldName>, <Argument1>);
        // *** At this point, fireVetoableChange can throw PropertyVetoException
        vetoableChangeSupport.fireVetoableChange(PROP_PROPERTY1, oldProperty1, property1);
        // Code: this.<FieldName> = <Argument1>;
        this.property1 = property1;
        // Code: propertyChangeSupport.firePropertyChange(<"FieldName" or Constant>, old<FieldName>, <Argument1>);
        propertyChangeSupport.firePropertyChange(PROP_PROPERTY1, oldProperty1, property1);
    }

    // *******************************************************
    // Getter and Setter for (only) Property Change Support
    // It does not throws PropertyVetoException
    public String getProperty2() {
        return property2;
    }

    public void setProperty2(String property2) {
        String oldProperty2 = this.property2;
        this.property2 = property2;
        propertyChangeSupport.firePropertyChange(PROP_PROPERTY2, oldProperty2, property2);
    }

    // *******************************************************
    // Methods for register listeners. It's generated only one time.
    // Should appear only in classes use property change support.
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    public void addVetoableChangeListener(VetoableChangeListener listener) {
        vetoableChangeSupport.addVetoableChangeListener(listener);
    }

    public void removeVetoableChangeListener(VetoableChangeListener listener) {
        vetoableChangeSupport.removeVetoableChangeListener(listener);
    }

}
```

**Comment by jGauravGupta** [comment]
Hi @neorevx ,

Thanks for sharing your experience, Please share the following details : 

>>_NB does not generate vetoable change support without property change support_
Is any logical reason ?

**Comment by neorevx** [comment]
I think javabeans binding (used in NB) don't track vetoable change, because it's not safe to check if property has effectively changed. Any vetoable listener can throw VetoableChangeException and break the property change. So it must comes before the PropertyChangeSupport.
With PropertyChangeSupport we know for sure that the property has changed. Then, javabeans binding use this support.

It's logical for NB with javabeans. But, I in other kind of project, maybe Vetoable support only can be useful. The original documentation [http://docs.oracle.com/javase/8/docs/api/java/beans/VetoableChangeSupport.html](http://docs.oracle.com/javase/8/docs/api/java/beans/VetoableChangeSupport.html) has an example with VetoableChangeSupport only. Four mode - vetoable only - can be good idea. :)

I think the field / column may have two new checkboxes:
[  ] Property Change Support
[  ] Vetoable Change Support

- none check: no supports
- one check: one specific support
- two check: both support

Specifics cases can be implemented with snippets.

**Comment by neorevx** [comment]
Hi!

Property change support is implented?
