### ISSUE TITLE
[DBModeler] - Please add context menu entry for tables (multiple) and database to view SQL.

### ISSUE THREAD

**Issue by Chris2011** [jGauravGupta/JPAModeler#107]
I saw inside your video about the DB Modeler, that atm it is only possible to create SQL from a JPA file but inside the generated SQL Visualizer, you have an option called View SQL. This is really missing inside the Services -> Database section. You only can grab structure, but it is not sql. If you recreate the table, then you can see the SQL and change it but this is not my intention.

https://github.com/jGauravGupta/JPAModeler/blob/0c0d5adfe9926ec12f13f76bda3bfeb95caf27ce/DB%20Modeler/src/org/netbeans/db/modeler/specification/model/scene/DBModelerScene.java#L235

at this point, I see that you use this only to get the SQL from the scene where the visualizer is open. So it would be very great to have an option on each table (Project independent, it is really for the Services -> Database section) -> right click on it, maybe multi select tables -> choose View DDL or SQL doesn't matter and the editor with the SQL should open.

I know this is not part of JPA Modeler but DB Modeler is part of JPA Modeler, maybe it should be independent from it too? So I thought that this could be a good place to have this functionality here. DataGrip, the JetBrains IDE has this functionality too and it is really handy.

Regards

Chris

**Comment by jGauravGupta** [comment]
Hi @Chris2011 ,

View SQL option is already exist in [netbeans > services > databases > table > editor] yet after many click, please have a look on attached screenshot : 
![sql_create](https://cloud.githubusercontent.com/assets/15934072/21489351/969709e6-cc0f-11e6-83fc-694c30a86f9b.png)

Once apache netbeans setup will be done, this functionality could be added there at global level (all or partial table selection or Tables node selection).

**Comment by Chris2011** [comment]
The problem is, that I do not expect this option after I view the data, this doesn't make sense. I want to grab the structure, what is current possible but not what I want, when I right click a table BEFORE I view data of it. And View SQL of the whole DB is not possible too. But ok it should be implemented into the NB code.

**Comment by Chris2011** [comment]
IMHO, we have View Data, View DB (Which comes from your plugin) and for the same action on a DB or on a Table, I would like to expect ViewSQL. DataGrip does the same and this is where I would expect it, from a UX perspective.
