### ISSUE TITLE
Arquillian support with JPA Optional<Type> attribute

### ISSUE THREAD

**Issue by jGauravGupta** [jGauravGupta/JPAModeler#113]
Arquillian test case are failing for entity with Optional<Type> attribute.

**Comment by slavb18** [comment]
May be there should be option to make optional methods complementary to regular getters ?

e.g. for property Entity entity;
Entity getEntity()  and Optional<Entity> optEntity() ?

**Comment by jGauravGupta** [comment]
To enable Java 8 Optional : Tools > Options > JPA Modeler > select Java 8
Optional return type
If you want to disable it specific to attribute then : Attribute >
properties > Basic properties > Optional return type

**Comment by slavb18** [comment]
Thank you !

2017-01-20 17:21 GMT+04:00 Gaurav Gupta <notifications@github.com>:
