### ISSUE TITLE
Not for NB Full

### ISSUE THREAD

**Issue by mariusfilip** [jGauravGupta/JPAModeler#115]
Tried to install JPAModeler on NB Full 8.2, I don't see all the plugins and then I try to create a modeler file, only one type appears.

Is JPAModeler compatible with NB Full version (the EE version)?

**Comment by jGauravGupta** [comment]
Please share the Build Info : 
NetBeans > Toolbar > Help > About > Product Version: NetBeans IDE 8.2 (Build 201609300101)

**Comment by mariusfilip** [comment]
I add the following:
  1) what my Plugins | Installed tab shows
  2) details on User Installed Plugins
  3) full content of About. This last section contains the build number

Product Version: NetBeans IDE 8.2 (Build 201609300101)

----------------------------------------------------
C/C++
HTML5
User Installed Plugins
Java SE
Java Card
Tools
PHP
JavaFX2
Groovy
Java Web and EE
Developing NetBeans
Java ME
Service Registry
Base IDE
----------------------------------------------------
Version: 1.0 Source: org-netbeans-jpa-modeler-lib.nbm, org-netbeans-jcode-rest.nbm, NetBeans Distribution, org-netbeans-jpa-modeler-jcre.nbm, org-netbeans-jpa-modeler-collaborate.nbm, NetBeans IDE 8.2 (Build 201609300101), org-netbeans-modeler-libs.nbm, org-netbeans-jcode-core.nbm, org-netbeans-jpa-modeler-dbre.nbm, org-netbeans-jpa-modeler.nbm, org-netbeans-jcode-mvc.nbm, org-jcode-docker.nbm, org-netbeans-jcode-javaee-generator.nbm, org-netbeans-jcode-util.nbm, org-netbeans-jpa-ri.nbm, org-netbeans-jcode-ng.nbm, org-netbeans-db-modeler.nbm, org-netbeans-jpa-modeler-installer.nbm  
Plugin Description
JConsole
NetBeans JConsole module: Sun JDK 5 and 6 Monitoring and Management support. Debug and run applications with JConsole. IMPORTANT NOTE: This module runs only on Sun JDK.
JavaScript2 jQuery
For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
JPA Classes Reverse Engineering
JPA Modeler supports reverse engineering by importing existing source code and create new ER diagrams. Visualize JPA classes & database models so you can see how elements such as attributes, relationships and other objects relate to each other without showing actual data.
DB Modeler
Database design is one of the key features of JPA Modeler.DB Modeler helps to create, modify, and design your models without the need to write complex SQL to create and edit objects, you’ll know exactly what you are working on. You can develop a complete database schema with just a few clicks.
Node.js Editor Support
Editor support for Node.js. For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
FindBugs Integration
FindBugs Integration
JavaScript2 PrototypeJs
Editor support for PrototypeJs framework. More about the framework you can read at http://prototypejs.org/ . For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
JPA Modeler Core
JPA Modeler is an open source graphical tool that enhances productivity and simplifies development tasks of creating complex entity relationship models. Using it developers can create JPA class, visualize & modify Database and automates JavaEE8 code generation. The JPA Modeler provides forward & reverse engineering capabilities, import models from existing database, generate complex SQL/DDL and much more.
Java Profiler (Command Runner Plugin)
Command Runner plugin enables invoking the underlying OS commands using Runtime.exec(String command) on session start (Session Starting and Session Started) and session end (Session Stopping and Sessiion Stopped). Can be used for various purposes including starting the profiled server, generating load etc.
jCode Core
JavaEE 8 source generation tool
NetBeans API Documentation
Includes a complete copy of the NetBeans API documentation for offline browsing and Javadoc index searching. Covers all of the official API modules plus some APIs considered under development.
Database Reverse Engineering
Working with legacy database becomes even more challenging when the documentation has been lost in time. Make it available again by importing the existing database and create new ER diagram. Visually study the table structures and their relationships.
JavaScript Jade Support
For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
JavaScript2 Knockout
For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
JMX
NetBeans JMX Module: JMX MBeans and JMX Manager development wizard. IMPORTANT NOTE: Starting from JMX NetBeans module version 3.1, the JConsole and Monitoring and Management features have been externalized into a separate module, named JConsole module.
JavaScript2 RequiereJs
Editor support for RequireJs framework For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
Modules installed: JPA Modeler Libraries, REST Generator, JavaScript2 PrototypeJs, JPA Classes Reverse Engineering, Collaboration, JavaScript2 Knockout, JMX, JavaScript2 jQuery, Modeler Libraries, NetBeans API Documentation, jCode Core, Database Reverse Engineering, JPA Modeler Core, JavaScript Jade Support, MVC Code Generator, Docker, JEE Generator, jCode Util, FindBugs Integration, Java Profiler (Command Runner Plugin), JPA RI, JavaScript2 RequiereJs, Node.js Editor Support, Angular JS, DB Modeler, JConsole, Installer
----------------------------------------------------
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 1
Java: 1.8.0_112; Java HotSpot(TM) 64-Bit Server VM 25.112-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_112-b15
System: Windows 10 version 10.0 running on amd64; Cp1252; en_GB (nb)
User directory: C:\Users\Marius Filip\AppData\Roaming\NetBeans\8.2
Cache directory: C:\Users\Marius Filip\AppData\Local\NetBeans\Cache\8.2

**Comment by jGauravGupta** [comment]
Looks like only 15 modules are installed in your ide but current release(**v2.8**) have **22 modules** , please refer the Installation Doc : http://jpamodeler.github.io/page.html?l=tutorial/Installation

And also share the screenshot of available modeler file type (issue).

**Comment by mariusfilip** [comment]
I removed all JPAModeler plugins and reinstalled them (22 of them). 

I will attach the screenshot in another message.

Version: 1.0 Source: org-netbeans-jpa-modeler-lib.nbm, org-netbeans-jcode-rest.nbm, NetBeans Distribution, org-netbeans-jpa-modeler-jcre.nbm, org-netbeans-jpa-modeler-collaborate.nbm, NetBeans IDE 8.2 (Build 201609300101), org-netbeans-modeler-libs.nbm, org-netbeans-jcode-core.nbm, org-netbeans-jpa-modeler-dbre.nbm, org-netbeans-jpa-modeler.nbm, org-netbeans-jcode-mvc.nbm, org-jcode-docker.nbm, org-netbeans-jcode-javaee-generator.nbm, org-netbeans-jcode-util.nbm, org-netbeans-jpa-ri.nbm, org-netbeans-jcode-ng.nbm, org-netbeans-db-modeler.nbm, org-netbeans-jpa-modeler-installer.nbm  
Plugin Description
jCode Core
JavaEE 8 source generation tool
JavaScript2 PrototypeJs
Editor support for PrototypeJs framework. More about the framework you can read at http://prototypejs.org/ . For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
JPA Modeler Core
JPA Modeler is an open source graphical tool that enhances productivity and simplifies development tasks of creating complex entity relationship models. Using it developers can create JPA class, visualize & modify Database and automates JavaEE8 code generation. The JPA Modeler provides forward & reverse engineering capabilities, import models from existing database, generate complex SQL/DDL and much more.
JPA Classes Reverse Engineering
JPA Modeler supports reverse engineering by importing existing source code and create new ER diagrams. Visualize JPA classes & database models so you can see how elements such as attributes, relationships and other objects relate to each other without showing actual data.
JConsole
NetBeans JConsole module: Sun JDK 5 and 6 Monitoring and Management support. Debug and run applications with JConsole. IMPORTANT NOTE: This module runs only on Sun JDK.
JavaScript2 Knockout
For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
Java Profiler (Command Runner Plugin)
Command Runner plugin enables invoking the underlying OS commands using Runtime.exec(String command) on session start (Session Starting and Session Started) and session end (Session Stopping and Sessiion Stopped). Can be used for various purposes including starting the profiled server, generating load etc.
Node.js Editor Support
Editor support for Node.js. For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
DB Modeler
Database design is one of the key features of JPA Modeler.DB Modeler helps to create, modify, and design your models without the need to write complex SQL to create and edit objects, you’ll know exactly what you are working on. You can develop a complete database schema with just a few clicks.
JMX
NetBeans JMX Module: JMX MBeans and JMX Manager development wizard. IMPORTANT NOTE: Starting from JMX NetBeans module version 3.1, the JConsole and Monitoring and Management features have been externalized into a separate module, named JConsole module.
JavaScript2 RequiereJs
Editor support for RequireJs framework For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
FindBugs Integration
FindBugs Integration
JavaScript Jade Support
For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
JavaScript2 jQuery
For the list of included fixed bugs please check http://wiki.netbeans.org/NetBeans8.2PatchesInfo.
NetBeans API Documentation
Includes a complete copy of the NetBeans API documentation for offline browsing and Javadoc index searching. Covers all of the official API modules plus some APIs considered under development.
Database Reverse Engineering
Working with legacy database becomes even more challenging when the documentation has been lost in time. Make it available again by importing the existing database and create new ER diagram. Visually study the table structures and their relationships.
Modules installed: JPA Modeler Libraries, REST Generator, JavaScript2 PrototypeJs, JPA Classes Reverse Engineering, Collaboration, JavaScript2 Knockout, JMX, JavaScript2 jQuery, Modeler Libraries, NetBeans API Documentation, jCode Core, Database Reverse Engineering, JPA Modeler Core, JavaScript Jade Support, MVC Code Generator, Docker, JEE Generator, jCode Util, FindBugs Integration, Java Profiler (Command Runner Plugin), JPA RI, JavaScript2 RequiereJs, Node.js Editor Support, Angular JS, DB Modeler, JConsole, Installer

**Comment by mariusfilip** [comment]
Yes, that was it, thank you.

I created two projects:
* Java Web Application with Maven
* Java Application with Maven

They both showed more File Types than just JPA Modeler and, moreover, the Web App showed more File Types than the plain App.
