### ISSUE TITLE
generate ?xml-stylesheet xml processing instruction

### ISSUE THREAD

**Issue by slavb18** [jGauravGupta/JPAModeler#116]
Hi!

JPA model could have global property like "xml stylesheet", to generate xml processing instruction,
e.g with value "../jpa_stylesheets/jpa_documentation.xsl" it could generate line 
```
<?xml-stylesheet type="text/xsl" href="../jpa_stylesheets/jpa_documentation.xsl"?>
```
To have some sort of model autodocumentation.

When I write this line in model file, and then edit model in GUI and save, this line dissappears, and I need to add it manually.

**Comment by jGauravGupta** [comment]
Hi @slavb18 ,
Are you talking about internal xml generated in modeler file? Why you care about it (any benefit) ? 
Can you provide more detail.

**Comment by slavb18** [comment]
I have xslt stylesheet to transform it to html documentation
https://github.com/ilb/jpa_stylesheets, to make it work automatically, i need to write this processing instruction

**Comment by jGauravGupta** [comment]
Hi @slavb18 ,
Please share the process of conversion to html e.g command, tool etc. 
And also share the generated html file.

**Comment by slavb18** [comment]
Hi!
With xml procesing instruction only need to open this file in browser, and it will do transformation.
Howewer this can be done on server side to. So, if you see my approach unsuitable, i will simple generate html files using maven plugin.


Generated from https://github.com/pembertonc/SGV-NAITS/blob/4fa5c3ff5702fa192519c66170a79df3ba47a71d/src/main/java/vc/gov/svgnaits/model/SVG-NAITS-Farmer-Model.jpa

[SVG-NAITS-Farmer-Model.html.zip](https://github.com/jGauravGupta/JPAModeler/files/693401/SVG-NAITS-Farmer-Model.html.zip)

 using command

```
xsltproc jpa_stylesheets/jpa_documentation.xsl SVG-NAITS-Farmer-Model.jpa  > SVG-NAITS-Farmer-Model.html
```

**Comment by jGauravGupta** [comment]
Sure, I will provide this functionality in next release.

**Comment by slavb18** [comment]
xslt stylesheet could be (possible) used in future to make button like "Export HTML Docs..."

**Comment by jGauravGupta** [comment]
Hi @slavb18 ,

Can you try to archive it with shell scripting.
e.g : read modeler file >inject stylesheet header > make tmp file > run xsltproc

**Comment by slavb18** [comment]
Yes, i can

**Comment by jGauravGupta** [comment]
As per my evaluation there could be multiple <?xml-stylesheet> which will make ui complex and not cohesive with JPA/class property panel and there is already a report generator module using which png, jpeg etc. can be generated.
In future , html report generator could be available.

So right now please fix at your end by shell scripting :)

**Comment by slavb18** [comment]
Ok, thank you
