### ISSUE TITLE
How to disable generation of @author tag in javadoc ?

### ISSUE THREAD

**Issue by slavb18** [jGauravGupta/JPAModeler#117]
How to disable generation of @author tag in javadoc in each class?
Or possible make fixed value for @author

When more than  one  person involved in modelling, there is continous @author change depended on who is generating classes

**Comment by jGauravGupta** [comment]
@author generation can't be disabled but in future release @author specific
to entity will be available .

**Comment by slavb18** [comment]
thanks!
