### ISSUE TITLE
XmlTransient with ManyToOne

### ISSUE THREAD

**Issue by slavb18** [jGauravGupta/JPAModeler#119]
Hi!

With bidirectional ManyToOne relation, corresponding OneToMany contains  annotation @XmlTransient , not listed in propery annotations (looks like hardcoded?)

May be this annotation should be visible in modeler, to make it more flexible (to make one or other side  of relation @XmlTransient, or possible custom use different annotation, e.g one can replace  @XmlTransient with @XmlInverseReference)

**Comment by jGauravGupta** [comment]
Please attach the sample modeler file.

**Comment by slavb18** [comment]
This is example, please see User class
`    @XmlTransient
    @OneToMany(targetEntity = Document.class, mappedBy = "user")
    private List<Document> documents;
`
[model.zip](https://github.com/jGauravGupta/JPAModeler/files/708772/model.zip)
