### ISSUE TITLE
@OrderColumn & @OrderBy annotation support

### ISSUE THREAD

**Issue by slavb18** [jGauravGupta/JPAModeler#121]
Hi!

How to add @OrderColumn annotation to property?
Does this possible in UI ?

https://wiki.eclipse.org/EclipseLink/Examples/JPA/2.0/OrderColumns

**Comment by jGauravGupta** [comment]
@OrderColumn support is not available now. ATM you can use custom snippet.

**Comment by jGauravGupta** [comment]
Next Enhancement #128 , #129 .
