### ISSUE TITLE
Missing Options

### ISSUE THREAD

**Issue by marckaraujo** [jGauravGupta/JPAModeler#122]
I have installed the last plugin for netbeans.

And some options are missing for create.
I already have tried to re-install and got same results.

![missing](https://cloud.githubusercontent.com/assets/3084181/22203855/20958360-e156-11e6-91f2-0fc99e12a77b.png)
![about_netbeans](https://cloud.githubusercontent.com/assets/3084181/22203857/23e45730-e156-11e6-890a-d010a86ff80f.png)

**Comment by jGauravGupta** [comment]
- Have you installed all plugin modules (currently 22 plugin in zip
   bundle and recent release v3.0) ?
   - If you have one existing modeler file (sample.jpa), Is modeling
   working for it ?
   - If you don't have existing modeler file then create empty sample.jpa
   file and check.

**Comment by marckaraujo** [comment]
- Yes, I installed all 22 plugin from v3.0.
- I have one file from another project, I have copied from there, and it works pretty well.

I just cant create a new one from the new file options.

**Comment by jGauravGupta** [comment]
Can you try to uninstall the Darcula LAF theme plugin and then try it once
after ide restart.

**Comment by marckaraujo** [comment]
Same problem.

![Uploading missing2.png…]()
