### ISSUE TITLE
Is Cacheable should be three state property

### ISSUE THREAD

**Issue by slavb18** [jGauravGupta/JPAModeler#123]
Hi!

Currently I can only check "Is Cacheable" property to make entity Cacheable, but can not add @Cacheable(false)

E.g.in  eclipselink all entities age Cacheable by default, and to make then not cacheable, i need 
@Cacheable(false)

Is Cacheable should be three state property: true/ false / default

**Comment by jGauravGupta** [comment]
Normally there is no need for 3 state but there are some case scenario where it is required : 
1. In eclipselink all entities age Cacheable by default, and to make then not cacheable, @Cacheable(false) required (reported by @slavb18 )
2. And If you want to override(e.g disable) caching property in subclass.
