### ISSUE TITLE
Embeddable @Column Property Precision & Scale ignored by View SQL Command

### ISSUE THREAD

**Issue by Mobidat** [jGauravGupta/JPAModeler#130]
When using BigDecimal in Java entity the View SQL Command generates DECIMAL(100) SQL Code. But many SQL data Bases like Maria DB don't like this. So I have to use the precision Property to generate the allowed DECIMAL(65). But when doing this in a embedded Entity the _@attribute overides section_ is used for generating the DECIMAL(XXX) values.  Using this instead of _Embeddable @column_ section in DB-View - I was blocked in creating the DB View from the jpa view.

**Comment by jGauravGupta** [comment]
Please attach the modeler file :)

**Comment by Mobidat** [comment]
[JpaDiagrammXT.zip](https://github.com/jGauravGupta/JPAModeler/files/735429/JpaDiagrammXT.zip)
The EmbeddedPhase Entity is critical

**Comment by jGauravGupta** [comment]
Please install the hot fix : https://github.com/jGauravGupta/JPAModeler/releases/tag/3.1.1

This fix is only for new created attribute, if you have already existing file then :
Open the file in xml mode > delete all lenth attribute by replacing 'length="255"' => ''
