### ISSUE TITLE
@Converts / @Convert / @Converter support

### ISSUE THREAD

**Issue by Mobidat** [jGauravGupta/JPAModeler#134]
In the annotations property of awt.color Type I added: @Convert(converter = ColorConverter.class)
In entity class creation mode this annotation is correct added to the Color property. But when creating DB tables with SQL-View command I get a **LONGBLOB** instead of the expected converted String Type in the MariaDB Table.

Is there a workaround to use jpa converter with jpa modeler??

I'm afraid this is a feature not a bug.... ;-)

**Comment by jGauravGupta** [comment]
Not yet, Will be available in next release :)
Thanks for pointing it out .
