### ISSUE TITLE
Does it possible to reverse-engeener classes with orm.xml

### ISSUE THREAD

**Issue by slavb18** [jGauravGupta/JPAModeler#135]
Hi!

Does it possible to reverse-engeener classes with orm.xml
Classes do not have any JPA annotations (@Entiity, @Basic,etc ),
but mapped using orm.xml 
Does it possible to reverse engeener them ?
Or the only possibility to reverse engeener generated database  in this case?

**Comment by jGauravGupta** [comment]
Not possible with ORM.xml. 
And reverse engineering is not fruitfully 100% : 
In case of DB REV-ENG , you will lost the Embedded , MappedSuperClass etc.
In case of Java Class REV-ENG , you will lost the custom snippet, constructor etc.

**Comment by slavb18** [comment]
Thanks!
