### ISSUE TITLE
Release for NetBeans Build 201610071157

### ISSUE THREAD

**Issue by Bolondri** [jGauravGupta/JPAModeler#139]
Hi! 

I'm trying to install this plugin but i'm afraid my netbean's build has no release. Will you release a update for this version?

Product Version: NetBeans IDE 8.2 (Build 201610071157)

Thanks in advance!

**Comment by jGauravGupta** [comment]
Hi @Bolondri ,
Please share the download link of this build.

**Comment by Bolondri** [comment]
Hi @jGauravGupta 

Spanish:
SHA-256: 133a49087cebf7dbbef40343bbbcc02ac6f151552eb4a11896202d34259a2e45
http://bits.netbeans.org/netbeans/8.2/community/bundles/netbeans-8.2-windows.exe

English:

SHA-256: c6df4acafb3b8583ec76a643b5df086583ad0bec86072166bc94c65c8731d837
http://download.netbeans.org/netbeans/8.2/final/bundles/netbeans-8.2-windows.exe

Maybe that's the problem. I've dowloaded the spanish one.

**Comment by jGauravGupta** [comment]
Yes, It will work with English version.

**Comment by jGauravGupta** [comment]
Release are only available for English version so closing this issue ,
