### ISSUE TITLE
Add redundant Serializable interface to entities inherited from AbstractClass  

### ISSUE THREAD

**Issue by Mobidat** [jGauravGupta/JPAModeler#143]
I deleted all "implements Serializable" code from entity classes, which are inherited from abstract entity class with the correct Serializable interface. 
Then I use JPA Diagram from reverse to generate a new JPA Diagramm. After this operation I delete all entities code and generate them new from the jpa diagramm.
The "implements Serializable" code was automatical generated for all classes. But only the abstract Superclass need it realy!

**Comment by jGauravGupta** [comment]
On new diagram creation "implements Serializable" interface added by default. 
To remove this : 
Click on diagram area > Global config > Interface > remove the Serializable

**Comment by Mobidat** [comment]
Tnx very much!
