### ISSUE TITLE
Partial Generation

### ISSUE THREAD

**Issue by pembertonc** [jGauravGupta/JPAModeler#150]
I upgraded to JPA Modeler 3.3 and cant generate all my classes.  Clicking on the partial Generation Button generates the Source.  It no longer gives the option to select what to generate.

**Comment by jGauravGupta** [comment]
In the attached pic, With Red Highlighted option , you can manage entities.
And Blue highlighted option , you can skip base application (user management , util , etc), in case application already generated.

![capture](https://cloud.githubusercontent.com/assets/15934072/23560297/f1f039aa-005f-11e7-89c7-0278c644c987.PNG)

**Comment by jGauravGupta** [comment]
Sorry for inconvenience , documentation is not yet available.

**Comment by jGauravGupta** [comment]
Re-open it  In case of any clarification , Happy to help you :)
