### ISSUE TITLE
Unable to include many-to-one to index

### ISSUE THREAD

**Issue by slavb18** [jGauravGupta/JPAModeler#155]
Unable to include many-to-one to index
Issue is like  #145, no field is available in selector on index creation

Thanks!

**Comment by jGauravGupta** [comment]
Hi @slavb18 ,
As per JPA Spec for **Primary Key** : it is not necessary to specify an index for a primary key, as the primary key index will be created automatically, however, the Index annotation may be used to specify the ordering of the columns in the index for the primary key.
So Primary Key should be part of DB Modeler with disabled checked checkbox.

For **Foreign Key** default index creation behavior varies , some db by default create index and other not, So it should be part of DB Modeler.

Not : This ticket will not support ordering of index.

**Comment by slavb18** [comment]
Also some times Composite index is required like basic field + foreign key
