### ISSUE TITLE
Move property up and down functionality missing in 3.5.1

### ISSUE THREAD

**Issue by slavb18** [jGauravGupta/JPAModeler#156]
Hi!

In previous releases the was option to move property up and down.
Move property up and down functionality missing in 3.5.1
Is this bug ?

**Comment by jGauravGupta** [comment]
Hi @slavb18 ,
Thanks for reporting issue . In v3.4 and v3.5 , Major architecture changes has been done for future DTO Modeler base. So whatever issue you are getting , please report, Thanks for co-operating :)

**Comment by jGauravGupta** [comment]
Please install v3.6 .
