### ISSUE TITLE
JDO Support

### ISSUE THREAD

**Issue by stevespringett** [jGauravGupta/JPAModeler#157]
This is an interesting project. Are there any plans on supporting JDO?

When developing for the cloud, we typically either use the native datastore API or we use JDO. We also use JDO when we don't know or care about what underlying database (relational or non-relational) is used.

I don't want this ticket to turn into a JDO vs JPA debate, but supporting only JPA seems a bit limiting to me.

**Comment by jGauravGupta** [comment]
Sorry , We don't have any plan for JDO support. Can you refer to any existing sample project.

**Comment by stevespringett** [comment]
Thanks for the info. I use JDO almost exclusively. It's obviously an older spec, but still widely used with v3.2 of the spec nearing completion.

As far existing sample projects... Several Apache projects use JDO including ISIS, Spark, Hive, and Zeppelin. Google App Engine is certainly one of the largest deployments, my employer is serving nearly 150M users daily with JDO (at least the Java components anyway), and my personal projects including Hakbot Origin and OWASP Dependency-Track all use JDO.

I will certainly keep this project in mind on the occasions where I do use JPA though. I usually reserve JPA for more traditional Java EE projects.

**Comment by jGauravGupta** [comment]
Sample project means any basic "hello world" JDO application available in github. So I will get the exact API details from basic running application because I don't have JDO knowledge.

**Comment by stevespringett** [comment]
Datanucleus has many examples, unfortunately most of them use XML configurations rather than annotations. So not that useful https://github.com/datanucleus/samples-jdo

Datanucleus is the JDO reference platform and they do have pretty good docs with inline code snippets:

http://www.datanucleus.org:15080/products/accessplatform_5_1/

**Comment by jGauravGupta** [comment]
@stevespringett thanks for providing info :)
