### ISSUE TITLE
Read about angular generator support

### ISSUE THREAD

**Issue by Chris2011** [jGauravGupta/JPAModeler#16]
I don't know where but I heard plans for creating controllers, services and so on for angular too with JPA modeler, is this right? What are the plans etc. pp?

**Comment by jGauravGupta** [comment]
Yes it is true : [Announced at NetBeans Day India](https://twitter.com/netbeans/status/723795152603516930)

Existing support : MVC 1.0, EJB , JSP(viewer)
Next Release v1.7 : REST Generator
Future Release Plan : Angular JS 1 and 2 generator

**Comment by Chris2011** [comment]
Really great, thx for the info :)

**Comment by jGauravGupta** [comment]
Angular JS 1 generator is now available (v2.5.1 beta)
