### ISSUE TITLE
Discriminator Value field disabled in base class

### ISSUE THREAD

**Issue by slavb18** [jGauravGupta/JPAModeler#160]
Hi!

Please see screenshot
![inheritance](https://cloud.githubusercontent.com/assets/2534896/23790807/15a65d7c-059a-11e7-9529-7de78be11ed7.png)

Discriminator Value field disabled in base class (root of hierarchy).
Unable to correctly persist class without discriminator in Eclipselink:

Caused by: Exception [EclipseLink-44] (Eclipse Persistence Services - 2.6.4.v20160829-44060b6): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Missing class indicator field from database row [ArrayRecord(

Also, I think non-abstract Entity with inheritance, but without "Discriminator Value" set could be marked as error in JPA modeler, becouse without "Discriminator Value" it leads to runtime error "Missing class indicator field ". I can file separate issue, if you see this applicable

**Comment by slavb18** [comment]
As workaround i added @javax.persistence.DiscriminatorValue annotation to class

**Comment by jGauravGupta** [comment]
No need for separate ticket. 
Yes , you will never stuck due to any limitation/issue of JPA Modeler with custom annotation/field etc.

**Comment by jGauravGupta** [comment]
Hi @slavb18 ,

> _Also, I think non-abstract Entity with inheritance, but without "Discriminator Value" set could be marked as error in JPA modeler, because without "Discriminator Value"_

Is error scanning really required ? 

As per JPA Spec : The DiscriminatorValue annotation is used to specify the value of the discriminator column for entities of the given type. The DiscriminatorValue annotation can only be specified on a concrete entity class. If the DiscriminatorValue annotation is not specified and a discriminator column is used, a provider-specific function will be used to generate a value representing the entity type.

**Comment by slavb18** [comment]
In Eclipselink  DiscriminatorValue is not generated automatically, only error issued.
I am using Integer type discriminator, and i need to manually search for unused value in hierarchy when i add new entity.
Of course automating such thing is great, but i don't know how could this be done, may be this is not trivial (e.g. scan all hierarchy and find next max used, then add +1 )

**Comment by slavb18** [comment]
Curently I am getting " Missing class indicator field from database row",
when i forget to fill  DiscriminatorValue. This is why I offered error mark, to see such errors in forward.

**Comment by slavb18** [comment]
May be this error is only eclipselink specific, i don't know how other providers work

**Comment by jGauravGupta** [comment]
May be eclipselink support default value only for String type where class name is default value.

**Comment by jGauravGupta** [comment]
Warning indicator seems good for this scenario instead of Error.

**Comment by slavb18** [comment]
Thank you very much!
