### ISSUE TITLE
NullPointerException at java.util.TreeMap.put

### ISSUE THREAD

**Issue by phejl** [jGauravGupta/JPAModeler#18]
https://netbeans.org/bugzilla/show_bug.cgi?id=255975

**Comment by jGauravGupta** [comment]
Not reproducible with current version 1.6 of JPA Modeler. 
Have you tried with version 1.6 ?

**Comment by jGauravGupta** [comment]
Fix : https://github.com/jGauravGupta/JPAModeler/releases/tag/1.7
