### ISSUE TITLE
Files created from model with extra spaces

### ISSUE THREAD

**Issue by javydreamercsw** [jGauravGupta/JPAModeler#19]
For some reason sometimes code is generated with extra spaces. See attached file.

Code is technically correct and compiles after the spaces are removed, but it can be tedious.

**Comment by javydreamercsw** [comment]
Referenced attachment.


[world.zip](https://github.com/jGauravGupta/JPAModeler/files/293698/world.zip)

**Comment by jGauravGupta** [comment]
Please share the environment details NetBeans IDE, JPA Modeler version , Operating System etc.
Is it ubuntu ?

**Comment by javydreamercsw** [comment]
Netbeans IDE 8.1, Ubuntu 14, JPA modeler 1.5.6

**Comment by javydreamercsw** [comment]
In some cases it was letters in others chunks of words.

**Comment by jGauravGupta** [comment]
Hi @javydreamercsw ,

This issue is not reproducible, may be it is specific to your environment (OS), Have you tried it with any other env.

**Comment by javydreamercsw** [comment]
No, I haven't.

**Comment by jGauravGupta** [comment]
Hi @javydreamercsw ,

Can you try it with other environment. I have already observed(not now, 1 year before) in Ubuntu OS with different text editor. I am sure this environment specific issue.

**Comment by jGauravGupta** [comment]
Requester is unresponsive and issue is not reproducible so is closed right now.
If you are getting the same issue also with different environment then reopen it.
