### ISSUE TITLE
Refactoring for school project

### ISSUE THREAD

**Issue by IJong** [jGauravGupta/JPAModeler#21]
For a school project we had to refactore an open source project.
This project was reccomended to us and so we refactored one of the classes.
We keep getting an error message because we don't have permission (see attached screenshot)

![sourcetree error](https://cloud.githubusercontent.com/assets/7326871/15806282/57827f26-2b40-11e6-9418-2980316851ea.PNG)

Can anyone tell us how we can get permission to create a pull request?

**Comment by jGauravGupta** [comment]
Are u following the below procedure for contribution : 
1-Fork the project
2-Make one or more well commented and clean commits to the repository. You can make a new branch here if you are modifying more than one part or feature.
3-Perform a pull request in github's web interface.

if it is a new Feature request, don't start the coding first. Remember to post an issue to discuss the new feature.

If the feature is well discuss and there are some +1 or the project owner approved it, assign the issue to yourself, then do the steps above.

Please share the more info.
Thanks!
Gaurav

**Comment by jGauravGupta** [comment]
Please check the following documentation : 
[https://github.com/jGauravGupta/JPAModeler/blob/master/CONTRIBUTING.md](https://github.com/jGauravGupta/JPAModeler/blob/master/CONTRIBUTING.md)
