### ISSUE TITLE
Display data type in diagram

### ISSUE THREAD

**Issue by michikommader** [jGauravGupta/JPAModeler#23]
Is it possible to display the data type of each (basic) attribute in the model view, like known from classical class diagrams? This would bring a better understanding of exported model images to persons unfamiliar with the model. I did not find any configuration option for this feature.

**Comment by jGauravGupta** [comment]
Hi @michikommader,  

Sure it will be available soon in next release v1.8
Added in Next release plan https://github.com/jGauravGupta/JPAModeler/blob/master/CHANGELOG.md

Thanks :)

**Comment by jGauravGupta** [comment]
Please try the new Alpha release v1.8 :
[https://github.com/jGauravGupta/JPAModeler/releases/tag/1.8](https://github.com/jGauravGupta/JPAModeler/releases/tag/1.8)
