### ISSUE TITLE
JPA Modeler crashes when I add embeddable

### ISSUE THREAD

**Issue by rodolpheJZ** [jGauravGupta/JPAModeler#27]
My modeler crashes for some reason when I add the embeddable XEngDescription to the XEngRootDataset class. Any help to fix this would be greatly appreciated. The modeler file has been attached as txt, due to the fact taht Github does not accept to upload files with jpa extensions.

[WeEngJPADiagram - Copy.jpa.txt](https://github.com/jGauravGupta/JPAModeler/files/338557/WeEngJPADiagram.-.Copy.jpa.txt)

**Comment by jGauravGupta** [comment]
Please try the new Alpha release v1.8 :
[https://github.com/jGauravGupta/JPAModeler/releases/tag/1.8](https://github.com/jGauravGupta/JPAModeler/releases/tag/1.8)

**Comment by jShiwaniGupta** [comment]
@rodolpheJZ  please acknowledge .

**Comment by rodolpheJZ** [comment]
Hi Shiwani,

Thank you very much for your quick help and professionalism. I had found a workaround to get my things to work at the time the bug showed up. I have not been able to test the bug fix yet. My apologies for not responding sooner. I have been extremely busy...

I will try before the end of the week and let you know. Jpa modeler is a great tool. It tremendously sped up my development time. Thanks for sharing this with the community.

Regards

Rudy Zerry

Sent from my iPhone

On Jul 13, 2016, at 12:56 AM, Shiwani Gupta <notifications@github.com<mailto:notifications@github.com>> wrote:


@rodolpheJZ<https://github.com/rodolpheJZ> please acknowledge .
