### ISSUE TITLE
JPA @lob option

### ISSUE THREAD

**Issue by krismorte** [jGauravGupta/JPAModeler#29]
I miss the option to mark a column with @Lob

**Comment by javafunnyexample** [comment]
Attribute > Property Panel > Basic Properties > **Field Type** >Type > ( Default | Temporal | Enumerated | **LOB** )

**Comment by jShiwaniGupta** [comment]
Attribute > Property Panel > Basic Properties > **Field Type** >Type > ( Default | Temporal | Enumerated | **LOB** )

**Comment by jShiwaniGupta** [comment]
@krismorte Please acknowledge ;)
