### ISSUE TITLE
Generate hashCode() and equals() Methods

### ISSUE THREAD

**Issue by krismorte** [jGauravGupta/JPAModeler#30]
I miss a option to generate this methods like the toString()

**Comment by jGauravGupta** [comment]
Please check this feature with v1.9 https://github.com/jGauravGupta/JPAModeler/releases/tag/1.9
Click on Entity -> Property panel -> Class Properties -> toString()

@krismorte Please acknowledge :)

and If you don't mind, please fill out [http://jpamodeler.github.io/p/register_company.html](http://jpamodeler.github.io/p/register_company.html)
