### ISSUE TITLE
Multiples Package para entidades en un mismo diagrama

### ISSUE THREAD

**Issue by enavarrom** [jGauravGupta/JPAModeler#39]
Buenas,

Cómo puedo crear en un modelo una o mas clases que se generen en distintos package.

**Comment by jShiwaniGupta** [comment]
Currently this feature is not available. 
Request has been approved , will be available in v2.7 :)

**Comment by enavarrom** [comment]
Thank!...i going to wait the v2.7. 

When is going to release the new version 2.7?

**Comment by jShiwaniGupta** [comment]
Currently Angular Client generator(v2.6) is in development(release is planned before JavaOne) and Multiple package feature has impact on all other generators(session bean , rest etc) so you may expect the release in mid of October.

**Comment by jGauravGupta** [comment]
Click on the Entity > Sub-Package
