### ISSUE TITLE
Add DateTime in Temporal Data Type

### ISSUE THREAD

**Issue by enavarrom** [jGauravGupta/JPAModeler#41]
In Temporal Data Type, only are available 3 types: Date, Time and TimeStamp. SQL Server have a problem when you use TimeStamp DataType, because you can't use more than 1 column of this type. Then, it's better for this DB, use DateTime or SmallDateTime datatype.

Can you add DateTime or SmallDateTime DataType for Temporal Data types in column properties of entities?

**Comment by jShiwaniGupta** [comment]
Can you please attach the snippet of current code , the expected code and error message if possible for future ref.

**Comment by jGauravGupta** [comment]
Datatype field is editable , you may add the type based on your pref.
Please send the more details and expected code snippet for embedded support from JPA Modeler.
