### ISSUE TITLE
Can't Install version 2.5 for NB 8.1

### ISSUE THREAD

**Issue by ismendoza** [jGauravGupta/JPAModeler#44]
Netbeans can't install JPA Modeler 2.5
Please see the image, 
https://yadi.sk/i/UkoEM-6FuY4ac

I tried to install with some previous version installed but it is not possible

**Comment by jGauravGupta** [comment]
Are you using NetBeans v8.1 ? JPA Modeler is compatible with only NetBeans v8.1.

**Comment by jGauravGupta** [comment]
Please share the complete NB version details 
**Menu > Help > About > Product Version: NetBeans IDE 8.1 (Build 201510222201)**

**Comment by ismendoza** [comment]
Product Version: NetBeans IDE 8.1 (Build 201511021428)

**Comment by jGauravGupta** [comment]
Can you also please send the error in text format so that I will translate it into English.

**Comment by ismendoza** [comment]
Algunos plugins necesitan que se instale el plugin Núcleo de base de datos.

Se necesita el plugin Núcleo de base de datos en la versión de implantación 201510222201.

El siguiente plugin se ha visto afectado
	JPA Modelere Core

Algunos plugins necesitan que se instale el plugin Modelo de metadatos de la base de datos.

Se necesita el plugin modelo de metadatos de la base de datos en la versión de
implantación 201510222201.

Algunos plugins necestian que se instale el plugin Verificación de JPA.

Se necesita el plugin Verificación de JPA en la versión de implantación 201510222201.

El siguiente plugin se ha visto afectado:
	JPA Modeler Core

Algunos plugins necesitan que se instale el plugin Utilidad del Usuario.

Se neesita el plugin Utilidades del usuario en la versión de implantación 201510222201.

El siguiente plugin se ha visto afectado:
	JPA Modeler Core

Algunos plugins no se han instalado para evitar posibles problemas de instalación.

**Comment by jGauravGupta** [comment]
Tried with the latest available version 8.1 **Product Version: NetBeans IDE 8.1 (Build 201510222201)**  from https://netbeans.org/downloads/ , It is installing fine. 
Currently can try this with available NetBeans IDE 8.1 release from https://netbeans.org/downloads/.

**Comment by ismendoza** [comment]
Thanks for your help

I downloaded netbeans 8.1 again and I installed it again and the build is the same (Build 201511021428)
(Netbeans 8.1 Java EE , Spanish, https://netbeans.org/downloads/) 
The same error when I try to install JPA Modeler 2.5

**Comment by ismendoza** [comment]
Thanks for your support, finally JPA Modeler 2.5 is installed !

**Comment by ovilladeamigo** [comment]
It's the same with netbeans 8.2

**Comment by jGauravGupta** [comment]
Right now we are working for netbeans 8.2 build will be available soon after some issue fix.

**Comment by jGauravGupta** [comment]
@ovilladeamigo Please download the latest v2.6.2 from here http://jpamodeler.github.io/page.html?l=p/download for NetBeans 8.2

Thanks for the patience :)

**Comment by balcalde** [comment]
Hi,
first, thanks a lot for this awesome tool. I use it on Microsoft Windows since a couple of weeks and I am already a big fan ;)
However, I tried to install it today on Linux and I get the same message as above (same dependencies are missing). 
The NetBeans I use is : NetBeans IDE 8.1 (Build 20151231-debian-8.1)
, i.e., the most recent available in the Synaptic Package Manager.
I hope you can help further.
Thanks!
[Install_ubuntu_error.pdf](https://github.com/jGauravGupta/JPAModeler/files/544596/Install_ubuntu_error.pdf)

**Comment by jGauravGupta** [comment]
Please install [NetBeans 8.2](https://netbeans.org/downloads/)  and [JPA Modeler plugin v2.6.3](http://jpamodeler.github.io/page.html?l=p/download)

**Comment by jGauravGupta** [comment]
Please install [NetBeans 8.2](https://netbeans.org/downloads/)  and [JPA Modeler plugin v2.6.3](http://jpamodeler.github.io/page.html?l=p/download)
