### ISSUE TITLE
Wildfly 10 Issue:  WELD-001456: Argument resolvedBean must not be null

### ISSUE THREAD

**Issue by Namphibian** [jGauravGupta/JPAModeler#47]
Hi.

Due to Glassfish being marked as not commercially supported anymore at some clients I cannot implement Glassfish as commercial support is an audit requirement. Thus I have been playing with this on WIldFly 10. I changed the persistence provider to Hibernate  in the persistence.xml as I expect at some clients they wont allow me to use EclipseLink either on their WildFly production servers.

I got the application to build but during deployment it stops at:

Deploying C:\wildfly-10.0.0.Final\standalone\deployments\JPAModellerDemo-1.0.war
{"WFLYCTL0080: Failed services" => {"jboss.persistenceunit.\"JPAModellerDemo-1.0.war#DEFAULT_PU\"" => "org.jboss.msc.service.StartException in service jboss.persistenceunit.\"JPAModellerDemo-1.0.war#DEFAULT_PU\": javax.persistence.PersistenceException: [PersistenceUnit: DEFAULT_PU] Unable to build Hibernate SessionFactory
    Caused by: javax.persistence.PersistenceException: [PersistenceUnit: DEFAULT_PU] Unable to build Hibernate SessionFactory
    Caused by: org.jboss.weld.exceptions.IllegalArgumentException: WELD-001456: Argument resolvedBean must not be null"}}

This seems like a known issue on WildFly see this link:

https://issues.jboss.org/browse/WFLY-2387

Also issue related logged on HIbernate JIRA

https://hibernate.atlassian.net/browse/HHH-8706

Also these StackOverflow items will be able to guide you.

http://stackoverflow.com/questions/35394384/org-jboss-weld-exceptions-illegalargumentexception-weld-001456-argument-resol

http://stackoverflow.com/questions/33891368/org-jboss-weld-exceptions-illegalargumentexception-weld-001456-argument-resolv

If there is a workaround in the current plugin? If not i am pretty sure I can figure it out but it is Fathers Day here today and I have to play dad to the kids for now.

I will try resolve and add notes when I get to it tomorrow or so.

**Comment by Namphibian** [comment]
Potential workaround found. 

The problem loos like it related to the Entity Listener on the AbstractAuditingEntity  class.

I changed this 
`@MappedSuperclass
@EntityListeners(AuditListner.class)
public abstract class AbstractAuditingEntity implements Serializable {`

To:
`@MappedSuperclass
//@EntityListeners(AuditListner.class)
public abstract class AbstractAuditingEntity implements Serializable {`

The error is resolved however running into SQL command statement errors on the deployment and run.


 Caused by: javax.persistence.PersistenceException: Unable to execute JPA schema generation create command [INSERT INTO ACCOUNT(ID, LOGIN, EMAIL, FIRST_NAME, LAST_NAME, LANG_KEY, ACTIVATED, CREATED_DATE, PASSWORD_HASH) VALUES (1001,  'user', 'user@example.com', 'User_F', 'User_L', 'en', 1, '2016-08-10 09:27:36.388', 'ee11cbb19052e40b07aac0ca060c23ee')]
    Caused by: org.postgresql.util.PSQLException: ERROR: column \"activated\" is of type boolean but expression is of type integer.
 

Will resolve this and log an issue separately for the SQL statement. I do believe PostgerSQL is interpreting 1 as an int the statement should probably be like 
` INSERT INTO ACCOUNT(ID, LOGIN, EMAIL, FIRST_NAME, LAST_NAME, LANG_KEY, ACTIVATED, CREATED_DATE, PASSWORD_HASH) VALUES (1001,  'user', 'user@example.com', 'User_F', 'User_L', 'en', 1::bool, '2016-08-10 09:27:36.388', 'ee11cbb19052e40b07aac0ca060c23ee')`

**Comment by Namphibian** [comment]
Hi. 

I found several SQL related issues on PostgreSQL when trying to deploy on Wildfly. I will post them soon.I have fixed them as well. Got to the landing page but still cant log in. Will investigate and resolve later.

**Comment by jShiwaniGupta** [comment]
Thanks for reporting the issue. Currently we have tested it using Payara and MySql/Derby DB. Once you will done with all fix, Please update here.

Really thanks for your support :)

**Comment by Namphibian** [comment]
Hi jShiwaniGupta 

I have found two or three PostgreSQL related SQL problems and also fixes. I will log these tonight on a new issue so we dont confuse the WildFly issue with the PostgreSQL issue.

**Comment by RandyHBH** [comment]
i found the same issue in my project, and apply the steps above and it run, but when i try to login using user:admin pass:admin do nothing, any tips.

regards and great work :) 👍

**Comment by jGauravGupta** [comment]
@RandyHBH ,
Please share more details like App Server and DB name. And also attach the project.
If you are using Wildfly, please try the latest v2.6.4.

**Comment by RandyHBH** [comment]
hi @jGauravGupta 
i am using Wildfly 10.1.0, PostgreSql 9.4, i also tried with the latest version available and still i can't login with user:admin pass:admin. I attach the full project. regards
[WildFlyJpaModeler.zip](https://github.com/jGauravGupta/JPAModeler/files/554851/WildFlyJpaModeler.zip)

**Comment by RandyHBH** [comment]
i fix the isuue when try to login with JPA and Hibernate. I change in the auto-generated User class the way of fetch de authorities.

### Before
@JsonIgnore
    @ManyToMany
    @JoinTable(name = "user_authority",
            joinColumns = {
                @JoinColumn(name = "user_id", referencedColumnName = "id")},
            inverseJoinColumns = {
                @JoinColumn(name = "authority_name", referencedColumnName = "name")})
    private Set<Authority> authorities = new HashSet<>();

### Now:
@JsonIgnore
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "user_authority",
            joinColumns = {
                @JoinColumn(name = "user_id", referencedColumnName = "id")},
            inverseJoinColumns = {
                @JoinColumn(name = "authority_name", referencedColumnName = "name")})
    private Set<Authority> authorities = new HashSet<>();

i found this isuue in stackoverflow and some info how to fix it using hibernate whitout change Lazy for Eager.
[http://stackoverflow.com/questions/11746499/solve-failed-to-lazily-initialize-a-collection-of-role-exception#](url)
[http://docs.jboss.org/hibernate/orm/3.3/reference/en/html/performance.html#performance-fetching-initialization](url)

**Comment by jGauravGupta** [comment]
"WELD-001456: Argument resolvedBean must not be null" issue tracking :
https://issues.jboss.org/browse/WFLY-2387
