### ISSUE TITLE
Error on install the latest version (2.5.8)

### ISSUE THREAD

**Issue by rafaeldev** [jGauravGupta/JPAModeler#53]
Hi everybody!
I had an error on install the latest plugin. Was used following tutorial: http://jpamodeler.github.io/page.html?l=tutorial/Installation

When I restart the Netbeans I had that message:

**Warning - Was not possible install some modules:**

- DB Modeler - The module named org.netbeans.jpa.modeler was needed and not was found;
- Database Reverse Engineering - The module named org.netbeans.jpa.modeler was needed and not was found;
- JPA Classes Reverse Engineering - The module named org.netbeans.jpa.modeler was needed and not was found;

**Additional Informations:**
My previous version was installed by this repository http://jpamodeler.github.io/updates.xml

PS.: Sorry for my English 😅

**Comment by jShiwaniGupta** [comment]
Hi @rafaeldev , 

v2.5.8 installation is tested and working fine with NetBeans v8.1. Can you uninstall the JPA modeler, jCode and netbeans modeler plugin and try again.

Please confirm the following info : 
 Product Version: NetBeans IDE 8.1 (Build 201510222201)
Java: 1.8.0_91; Java HotSpot(TM) Client VM 25.91-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_91-b15

**Comment by rafaeldev** [comment]
Hi @jShiwaniGupta ,

I uninstall that plugins:
- Angular JS
- Collaboration
- Database Reverse Engineering
- DB Modeler
- Installer
- jCode Util
- JEE Generator
- JPA Classes Reverse Engineering
- MVC Code Generator
- REST Generator

After I install that plugins again.
**Now is work very fine!!!**

I think I had restart the IDE after uninstalling the old plugin. This may have helped the problem...

Thank you!

**See my info:**
Product Version: NetBeans IDE 8.1 (Build 201510222201)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b08, mixed mode)
Java(TM) SE Runtime Environment (build 1.8.0_40-ea-b04)
