### ISSUE TITLE
no @Basic(optional = false)

### ISSUE THREAD

**Issue by thomas-mc-work** [jGauravGupta/JPAModeler#56]
I'm having a field in the model file that is not optional and thus not nullable. When i now generate the source code then field receives the annotation `@Column(nullable = false)` and also a `@Basic` annotation - but not `@Column(nullable = false`. Is there a reason for that behaviour? As far as i understand [from this post](http://stackoverflow.com/a/2899828/2854723) adding this would lead to validating the value at runtime.

**Comment by jShiwaniGupta** [comment]
May you please attach the jpa modeler file and explain in more details.

**Comment by jGauravGupta** [comment]
@Basic(optional = false) Issue has been fixed , please install the v2.6.2 for NetBeans 8.2 from here http://jpamodeler.github.io/page.html?l=p/download
