### ISSUE TITLE
feature request: @Version handling

### ISSUE THREAD

**Issue by thomas-mc-work** [jGauravGupta/JPAModeler#57]
It would be nice to have a way to handle columns that are designated to handle the version number for optimistic locking - marked with the `@Version` annotation. It would be great to see this feature integrated into the modeling and also in code generation and reverse engineering. Also shortcuts for adding the version flag to all tables/entites would be helpful for initialization.

**Comment by thomas-mc-work** [comment]
Now I see that you have a feature to add generic annotations to any columns. That's good so far, but a tight integration would be better. Another feature idea: In the default setting all version related columns could be hidden because as a database designer i don't care about them normally. They should onyle be there for JPA. Maybe their presence can be visualized by an icon in the header bar of the table.

**Comment by jShiwaniGupta** [comment]
@Version support is already available in the jpa modeler and you don't need to use the generic annotation stuff for these, please check the following links : 
http://jpamodeler.github.io/page.html?l=tutorial/AttributeMapping#VM


Thanks for the second suggestion but from my view, version column should not be hidden in the database modeler, may be developer want to change the column name.

**Comment by thomas-mc-work** [comment]
Great, that's what i was looking for.

I noticed an issue with the diagram creation from reverse engineering: When the existing `@Version` properties have other annotation then the process doesn't recognize them properly.

Working:

    @Version
    private int version;

Not Working:

    @Basic(optional = false)
    @NotNull
    @Column(nullable = false)
    @Version
    private int version;

**Comment by jGauravGupta** [comment]
@Version and @Basic could not be used for same property.

Correct me if I am wrong by proper details and jpa spec sections

**Comment by thomas-mc-work** [comment]
You're probably right. It's up to you what to do only when creating the JPA DIagram from reverse engineering. Even if it's wrong it might stll be useful to apply the `@Version` annotation, even if the definition isn't clean.

**Comment by jShiwaniGupta** [comment]
Yes, we have already tried to captured and fix, most of the corrupted jpa entities class , relationship case scenario to diagram in reverse engineering action but there may be "N" case scenario.

For this case scenario, If Version will have priority then one day some will report that @Basic information is lost.
