### ISSUE TITLE
feature request: move area of detail with middle mouse button

### ISSUE THREAD

**Issue by thomas-mc-work** [jGauravGupta/JPAModeler#58]
When i view the model and it doesn't fit into the window then i have either the scrollbars or the Navigator to move the visible area. It would be nice to move by clicking the middle mouse button and then dragging the section (like in [MySQL Workbench](http://mysqlworkbench.org/)).

**Comment by jShiwaniGupta** [comment]
We have already provided the support for movement with : 

- Left, right, up, down arrow button
- Scroll bar
- BirdView panel
- and with some drag hand button available on the jpa modeler tool bar

If you have any query and issue then , please revert.
