### ISSUE TITLE
Entity / JPA Diagram is inconsistent with boolean fields

### ISSUE THREAD

**Issue by Mobidat** [jGauravGupta/JPAModeler#61]
Generating Entity Code from JPA Diagramm with Boolean Fields - you get access Methods with is prefix. But if you want to create JPA Diagramm from Entity Code this Fields with is Prefix Methods are ignored in the Diagramm. Primitive "boolean" Fields are always ignored - only Boolean Wrapper Objects with get Methods are correct copied in JPA Diagramm.

**Comment by jGauravGupta** [comment]
Thanks for reporting the issue.
