### ISSUE TITLE
Does not work under wildfly 10

### ISSUE THREAD

**Issue by evilkid** [jGauravGupta/JPAModeler#66]
I have tried to generate a simple single entity under wildfly 10, and create a controller using rest, 
but i keep getting: 
[PersistenceUnit: WILDFLY_PU] Unable to build Hibernate SessionFactory

You can find the project attached.
Does this plugin support wildfly server?

[WildflyTest.zip](https://github.com/jGauravGupta/JPAModeler/files/518657/WildflyTest.zip)

**Comment by jShiwaniGupta** [comment]
It should also work on wildfly, please ensure the jndi and persistence unit are correct ?
Which database are you using ?

**Comment by evilkid** [comment]
Yes, im sure the JNDI and the PU are correct, because when i generate only the entites it does work.
But i found out that removing the "@EntityListeners(AuditListner.class)" from "AbstractAuditingEntity" class "resolved" the problem.
Butit when launching the application, and trying to login using the "user" account or the "admin" account, it fails, and consulting the browser console, i get 500 internal errors on both the "/api/account" and "/api/authenticate".

**Comment by jShiwaniGupta** [comment]
Currently, we are not using **liquidbase**, so it is not portable across db for demo user entry insertion.
Also please check that the user entry is available in your db.

your feedback will be highly appreciated :)

**Comment by evilkid** [comment]
Ah forgot to mention im using MySQL. I have made tiny changes in the insert.sql, just change update the account inserting line from "name" to `name` in order for it to pass.
And yes, both of the entries are in the database.

**Comment by jShiwaniGupta** [comment]
As per your JPA Modeler file, you are generating Entity named "User" and JPAModeler is also generating some system entity like **Authority, User**. So may be, it leads some conflicts in source code generation.

Currently, you should not use entity named Authority, User in the diagram. 
May be , in the feature, we will have option to modify system generated entity like Authority, User from JPA Modeler diagram (as you are currently doing) .

**Comment by evilkid** [comment]
Yes, I noticed that later in the night, I even tried with other names (like the default one, "entity_1").

**Comment by jShiwaniGupta** [comment]
And for "entity_1", you are still getting error.
Can upload the complete project with AngularJS files.

**Comment by evilkid** [comment]
Ofcourse, here it is: 
[TestTheWildfly.zip](https://github.com/jGauravGupta/JPAModeler/files/519386/TestTheWildfly.zip)

**Comment by jShiwaniGupta** [comment]
Yes, I am observing the login issue with the Wildfly 10 + MySql but the same code is working fine with Payara + Mysql. 

Issue : JWTAuthenticationFilter.resolveToken() -> request.getHeader(Constants.AUTHORIZATION_HEADER)

**"Authorization"** header is missing in case of wildfly server.

Will update you soon about the fix.

**Comment by evilkid** [comment]
Thank you.

**Comment by jShiwaniGupta** [comment]
**Solution for "Authorization" header :**  add "X-Requested-With" header
>src\main\webapp\app\blocks\interceptor\auth.interceptor.js
if (token) {
                config.headers.Authorization = 'Bearer ' + token;
                config.headers["X-Requested-With"] = "XMLHttpRequest";
           }

**Reference :** https://developer.jboss.org/thread/248266

**Comment by jShiwaniGupta** [comment]
Another issue : 
```
@SessionScoped
public class SecurityUtils implements Serializable {

    @Context
    private SecurityContext securityContext;

    public String getCurrentUserLogin() {
        if (securityContext == null || securityContext.getUserPrincipal() == null) {
            return null;
        }
        return securityContext.getUserPrincipal().getName();
    }
}
```

SecurityContext is not injected in case of wildfly.

**Comment by evilkid** [comment]
I cant really say which component failed, but yeah, even after adding the request header it didnt not work.

**Comment by jShiwaniGupta** [comment]
Wildfly SecurityContext injection fix : 
```
import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.SecurityContext;

/**
 * Utility class for Security.
 */
@SessionScoped
@Path("/api")
public class SecurityUtils implements Serializable {

    @Context
    private SecurityContext securityContext;

    @Path(value = "/current_user")
    @GET
    public String getCurrentUserLogin() {
        if (securityContext == null || securityContext.getUserPrincipal() == null) {
            return null;   
        }
        return securityContext.getUserPrincipal().getName();
    }
}
```

Working fine with above fix, 
Environment details : Wildfly 10, Hibernate 2.1, MySql DB

**Comment by evilkid** [comment]
Thank you for your interest in this issue.
Yes i can confirm that this fix works.
