### ISSUE TITLE
Could not install JPA modeler as plugin to Netbeans 8.2

### ISSUE THREAD

**Issue by kreifeurm** [jGauravGupta/JPAModeler#68]
Hi, I ma facing a problem of dependencies and version when trying installing JPA modeler v2.5.3 within Netbeans 8.2.
Here is the errors:
_Some plugins require plugin org.netbeans.jpa.specification to be installed.
The plugin org.netbeans.jpa.specification is requested in version 2.5.10.  The following plugin is affected:       JPA Modeler Core 
Some plugins require plugin org.netbeans.modeler to be installed.
The plugin org.netbeans.modeler is requested in version 1.0.  The following plugin is affected:       JPA Modeler Core 
Some plugins require plugin org.netbeans.modeler.properties to be installed.
The plugin org.netbeans.modeler.properties is requested in version 1.0.  The following plugins are affected:       Collaboration       JPA Modeler Core 
Some plugins require plugin org.netbeans.modeler.specification to be installed.
The plugin org.netbeans.modeler.specification is requested in version 1.0.  The following plugins are affected:       Collaboration       JPA Modeler Core 
Some plugins require plugin org.netbeans.orm.converter to be installed.
The plugin org.netbeans.orm.converter is requested in version 1.0.  The following plugin is affected:       JPA Modeler Core  Some plugins not installed to avoid potential installation problems._

I can only cancel the plugin installation.

Thanks for the help.

Moh. kreifeur

**Comment by jGauravGupta** [comment]
Please try the latest version v2.6.3 

**Download Page :** jpamodeler.github.io/page.html?l=p/download
**Download Link :** http://plugins.netbeans.org/download/plugin/8637

If you are still getting the same problem in installation of 2.6.3 then please share your netbeans build version detals : **Help > About > Product Version: NetBeans IDE 8.2 (Build 201609300101)**

**Comment by kreifeurm** [comment]
Got the same error
Here are more infos about my settings:
_Product Version: NetBeans IDE 8.2 (Build 201609300101)
Java: 1.8.0_102; Java HotSpot(TM) 64-Bit Server VM 25.102-b14
Runtime: Java(TM) SE Runtime Environment 1.8.0_102-b14
System: Windows 7 version 6.1 running on amd64; Cp1252; en_CA (nb)
User directory: C:\Users\mkreifeu\AppData\Roaming\NetBeans\8.2
Cache directory: C:\Users\mkreifeu\AppData\Local\NetBeans\Cache\8.2_

Thank you

**Comment by jGauravGupta** [comment]
Build version are same so please attach the binary here that you were trying.

**Comment by kreifeurm** [comment]
HI,
Here attached the binary

Thanks for the help.

KREIFEUR Mohamed
[1476200264_JPA_Modeler_v2.6.3_NBv8.2.zip](https://github.com/jGauravGupta/JPAModeler/files/525352/1476200264_JPA_Modeler_v2.6.3_NBv8.2.zip)

**Comment by jGauravGupta** [comment]
Attached binary installed successfully with NetBeans version 8.2 : 

**Product Version: NetBeans IDE 8.2 (Build 201609300101)
Java: 1.8.0_91; Java HotSpot(TM) Client VM 25.91-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_91-b15
System: Windows 8.1 version 6.3 running on x86; Cp1252; en_US (nb)
User directory: C:\Users\jGauravGupta\AppData\Roaming\NetBeans\8.2
Cache directory: C:\Users\jGauravGupta\AppData\Local\NetBeans\Cache\8.2**


![1](https://cloud.githubusercontent.com/assets/15934072/19337339/db8bba9c-9131-11e6-90b8-e62ec3bf73e1.PNG)
![2](https://cloud.githubusercontent.com/assets/15934072/19337341/e4e6fef8-9131-11e6-87e6-f1f8d9f827a1.png)

**Comment by jGauravGupta** [comment]
Had you imported NetBeans 8.1 configurations to NetBeans 8.2 after installation. Please share the installed plugin list (tools > plugins > installed).

**Comment by kreifeurm** [comment]
Yes  I did. May be the configuration import from 8.1 to 8.2 is causing the problem ?

Here are the list of installed plugin:
![image](https://cloud.githubusercontent.com/assets/4519456/19351787/200b4a86-912b-11e6-91aa-f07bf6037f1e.png)
![image](https://cloud.githubusercontent.com/assets/4519456/19351802/3392649a-912b-11e6-8f5c-0623e2db31a3.png)
![image](https://cloud.githubusercontent.com/assets/4519456/19351817/462d90f2-912b-11e6-8535-f51f426f2218.png)

**Comment by kreifeurm** [comment]
Hi, 
I found the problem after spending more time. I added manually the plugin one by one. The installation was finished successfully after some security warnings.

I think not all *.nbm were imported completely.  I think the problem were from my side rather from the tool it self.

Thanks a lot for  the help

Mohamed Kreifeur
