### ISSUE TITLE
Error when generating controller with composite Primary Key 

### ISSUE THREAD

**Issue by evilkid** [jGauravGupta/JPAModeler#69]
There was an error when generating a controller for an entity with composite foreign keys, when generating, this error is printed in the console when executing the generate: 

```
        ##################################### Error #####################################       

Primary key "id"  >     Primary key "id" missing in Entity "null" (auto generated required)

Task Successful (total time: 28 seconds)

```

In the entity (the one with the composite key) controller, this is what's getting generated (get/id): 

```
/**
     * GET /:Expression pkName is undefined on line 106, column 16 in unknown. :
     * get the "Expression pkName is undefined on line 106, column 37 in
     * unknown." entity_3.
     *
     * @param Expression pkName is undefined on line 108, column 17 in unknown.
     * the Expression pkName is undefined on line 108, column 31 in unknown. of
     * the entity_3 to retrieve
     * @return the Response with status 200 (OK) and with body the entity_3, or
     * with status 404 (Not Found)
     */
    @Path("/{Expression pkName is undefined on line 116, column 16 in unknown.}")
    @GET
    public Response getEntity_3(@PathParam("Expression pkName is undefined on line 118, column 53 in unknown.") Expression pkType 
        is undefined on line 118, column 65 in unknown. Expression pkName is undefined on line 118, column 75 in unknown.) {
        log.debug("REST request to get Entity_3 : {}", Expression pkName is undefined on line 119, column 64 in unknown
        .);
        Entity_3 entity_3 = entity_3Facade.find(Expression pkName is undefined on line 120, column 66 in unknown
        .);
        return Optional.ofNullable(entity_3)
                .map(result -> Response.status(Response.Status.OK).entity(entity_3).build())
                .orElse(Response.status(Response.Status.NOT_FOUND).build());
    }
```

**Comment by jShiwaniGupta** [comment]
Please attach the modeler file.

**Comment by evilkid** [comment]
Sorry forgot to attach.

[TestPK.zip](https://github.com/jGauravGupta/JPAModeler/files/526895/TestPK.zip)

**Comment by jShiwaniGupta** [comment]
Sure, it will be fixed soon.
Whatever you are expecting/missing from JPA, Session Bean, REST Controller will be done but in front-end we are using java hispter Angular JS template so UI side have some restriction like simple auto generated primary key named "id".

We will try to cover these types of limitation in Angular JS 2 version.

Fix for this jax-rs issue will be available ASAP.

**Comment by evilkid** [comment]
Ok thank you, I'll be waiting.

**Comment by jGauravGupta** [comment]
Hi @evilkid ,
Generator for composite primary key (IdClass/Embeddable) is available for both REST and Arquillian.

** Generator for Derived Identities is still not developed.
Ref : http://jpamodeler.github.io/page.html?l=tutorial/DerivedIdentities

**Comment by evilkid** [comment]
Awesome job, thank you.
