### ISSUE TITLE
Cannot reopen jpa diagram in modeler view

### ISSUE THREAD

**Issue by piratron** [jGauravGupta/JPAModeler#7]
When I close the  JPA Modeler diagram  and I want to reopen it (right click or directly), I always get the XML structure of the diagram file in the editor.

Product Version: NetBeans IDE 8.1 (Build 201510222201)
Updates: NetBeans IDE is updated to version NetBeans 8.1 Patch 1
Java: 1.8.0_77; Java HotSpot(TM) 64-Bit Server VM 25.77-b03
Runtime: Java(TM) SE Runtime Environment 1.8.0_77-b03

**Comment by jGauravGupta** [comment]
Could you please help with the following queries :

1. Is this problem is specific to some file or for all files (if for some files then attach the files).
2. Is **Edit In Modeler** option is visible. (Right click on modeler file > Edit In Modeler)
3. Is there any exception is shown in bottom task bar of netbeans.
4. Is it possible for you, to reproduce the issue in another netbeans version .

**Comment by piratron** [comment]
1. The problem exists for all files.
2. The **Edit in Modeler** Option is NOT visible. Only the normal **Open** option is visible.
3. There is no excpetion shown.
4. No, sorry I can't.

**Comment by piratron** [comment]
Hi Gaurav,

I try it out in NetBeans 8.0.2 with **JPA Modeler 0.9** and I can see the **Edit in Modeler** when I use the right click on the file.

**Comment by piratron** [comment]
1. The problem exists for all files.
2. The Edit in Modeler Option is NOT visible. Only the normal Open option is visible.
3. There is no exception shown.
4. I try it out in NetBeans 8.0.2 with JPA Modeler 0.9 and I can see the Edit in Modeler option when I use the right click on file.

Von: Gaurav Gupta [mailto:notifications@github.com]
Gesendet: Mittwoch, 13. April 2016 13:21
An: jGauravGupta/JPAModeler
Cc: Stelzner, Lars
Betreff: Re: [jGauravGupta/JPAModeler] Cannot reopen jpa diagram in modeler view (#7)


Could you please help with the following queries :
1.      Is this problem is specific to some file or for all files (if for some files then attach the files).
2.      Is Edit In Modeler option is visible. (Right click on modeler file > Edit In Modeler)
3.      Is there any exception is shown in bottom task bar of netbeans.
4.      Is it possible for you, to reproduce the issue in another netbeans version .

**Comment by jGauravGupta** [comment]
Previously which JPA Modeler version you were using ? And could you install and check the latest version 1.5.4 [http://plugins.netbeans.org/plugin/53057/jpa-modeler](http://plugins.netbeans.org/plugin/53057/jpa-modeler)

**Comment by piratron** [comment]
Hi,

I have re-installed the plug in 1.5.4 but the problem still exists. ☹

Best regards
Lars Stelzner




Von: Gaurav Gupta [mailto:notifications@github.com]
Gesendet: Donnerstag, 14. April 2016 05:42
An: jGauravGupta/JPAModeler
Cc: Stelzner, Lars
Betreff: Re: [jGauravGupta/JPAModeler] Cannot reopen jpa diagram in modeler view (#7)


Previously which JPA Modeler version you were using ? And could you install and check the latest version 1.5.4 http://plugins.netbeans.org/plugin/53057/jpa-modeler

**Comment by piratron** [comment]
Hi,

I make another try with Netbeans 8.0.2, JDK 1.8 and JPA Modeler 1.5.4 and a got the same problem.
When I create an new diagram it is opened in the modeler view. After closing the diagram and reopened it I got the XML structure.

Do you have an idea?

Best regards
Lars

Von: Gaurav Gupta [mailto:notifications@github.com]
Gesendet: Donnerstag, 14. April 2016 05:42
An: jGauravGupta/JPAModeler
Cc: Stelzner, Lars
Betreff: Re: [jGauravGupta/JPAModeler] Cannot reopen jpa diagram in modeler view (#7)


Previously which JPA Modeler version you were using ? And could you install and check the latest version 1.5.4 http://plugins.netbeans.org/plugin/53057/jpa-modeler

**Comment by jGauravGupta** [comment]
I will try again to reproduce it in same environment .
Which operating system are you using ?

**Comment by piratron** [comment]
Hi,

I am using WIN7 here.

I have tried it under WIN10 with NetBeans 8.1, JDK 1.8 and JPA Modeler 1.5.4 (at home ;-) ) and have no problems.



Von: Gaurav Gupta [mailto:notifications@github.com]
Gesendet: Freitag, 15. April 2016 06:13
An: jGauravGupta/JPAModeler
Cc: Stelzner, Lars
Betreff: Re: [jGauravGupta/JPAModeler] Cannot reopen jpa diagram in modeler view (#7)


I will try again to reproduce it in same environment .
Which operating system are you using ?

**Comment by jpamodeler** [comment]
fixed : https://github.com/jGauravGupta/JPAModeler/releases/tag/1.5

**Comment by jGauravGupta** [comment]
fixed : https://github.com/jGauravGupta/JPAModeler/releases/tag/1.5

**Comment by piratron** [comment]
Hi,

it seems it works! Thank you!

Best Regards
Lars

Von: Gaurav Gupta [mailto:notifications@github.com]
Gesendet: Donnerstag, 21. April 2016 07:47
An: jGauravGupta/JPAModeler
Cc: Stelzner, Lars; Author
Betreff: Re: [jGauravGupta/JPAModeler] Cannot reopen jpa diagram in modeler view (#7)


Closed #7<https://github.com/jGauravGupta/JPAModeler/issues/7>.
