### ISSUE TITLE
NamedQueries generator problems

### ISSUE THREAD

**Issue by destanque** [jGauravGupta/JPAModeler#77]
When generated namequerys since JPAModeler, generated namedquery from attributes deleted in the entity.

Enviroment 
Netbean 8.2
glassfish  4.1.1

Hello, when an entity-attribute is deleted in the JPAModeler and you want generate de namedqueries for each entity. In properties entity-Properties -> Query -> Name Queries click the button and raise the window entity-Name Queries in the list of attributes you can select the entity attributes deleted.
I have not the  JPModeler file now but I checked  it

**Comment by jGauravGupta** [comment]
Can you please explain the issue in more details with example and issue generation scenario or with attached JPA Modeler file.

**Comment by jGauravGupta** [comment]
Issue is not much clear and user is unresponsive  but following settings option is related to this issue : 
**Tools > Options > JPA Modeler > Code > Delete  @NamedQuery on attribute removed**
