### ISSUE TITLE
Problems angularJS  interfaces generator 

### ISSUE THREAD

**Issue by destanque** [jGauravGupta/JPAModeler#78]
The relationship (unidirectional one to many relation ) and (many to one relation) do  not generated the fields B in A. 
Example 
Class A
  field  name

Class B
  field number

A contains a list<B> do not generated the selecte component for B in the interface create A.
A contains a field <B> do not generated the selecte component for B in the interface create A.

**Comment by jGauravGupta** [comment]
JPA Modeler is using the Angular JS UI template from [Java Hipster](https://github.com/jhipster/generator-jhipster) generator. So you mar raise the concern [here](https://github.com/jhipster/generator-jhipster/issues)
