### ISSUE TITLE
Add support to extend class / implement interface

### ISSUE THREAD

**Issue by neorevx** [jGauravGupta/JPAModeler#79]
Hi,

i'm using JPA Modeler and i'm very greatfull.
But i need to implements some interfaces in some entities.
I tried do it with Snippets, but there's no way to set 'implements'.
I think 'implements interface' (maybe throught snippets) is a good enhancement.

Ty.

**Comment by jGauravGupta** [comment]
Support for both extends / implements external classes will be available,

**Comment by jGauravGupta** [comment]
Please install v2.6.5 : https://github.com/jGauravGupta/JPAModeler/releases/tag/2.6.5
