### ISSUE TITLE
inheritance Joined strategy

### ISSUE THREAD

**Issue by mehaouihoussem** [jGauravGupta/JPAModeler#80]
Hello sir

I have a question ,why the generated tables does not have a primay key  when we use Joined inheritance  strategy??

**Comment by jGauravGupta** [comment]
In Joined inheritance strategy, the root of the class hierarchy is represented by a single table, and each subclass has a separate table that contains only those **fields specific to that subclass**. That is, the subclass table does not contain columns for inherited fields or properties. The subclass table also has a column or columns that represent its primary key, which is a **foreign key to the primary key of the superclass table**.
