### ISSUE TITLE
Visualize DB reports Enum as not serializable

### ISSUE THREAD

**Issue by pembertonc** [jGauravGupta/JPAModeler#81]
When i try to visualize the Database,  this exception.  The Gender Type is an enum,  the attribute for the class is marked as @Enumerated(EnumType.STRING) in the code.  This worked the last time I used it with out the JPA Modeler.   Is this a bug, or is there something I am missing.

Solved: The Modeler ignores the Enumerated When reversing engineering.  However setting the field Type type to Enumerated, makes the problem go away.  _Note: Adding  @Enumerated(EnumType.STRING)  as an Annotation also did not resolve the problem_

**Comment by jGauravGupta** [comment]
Really Thanks for reporting the issue, It was reverse engineering issue, btw custom annotation, interface are not evaluated just used for template and code generation .
Please install v2.6.5 : https://github.com/jGauravGupta/JPAModeler/releases/tag/2.6.5
