### ISSUE TITLE
Enum FetchType import is not generated

### ISSUE THREAD

**Issue by neorevx** [jGauravGupta/JPAModeler#82]
Hi,

when i use FetchType.LAZY, the import for this enum (javax.persistence.FetchType) is not generated.

**Comment by neorevx** [comment]
I think it's not fixed.
Import of CascadeType also not generated.

**Comment by jGauravGupta** [comment]
Hi @neorevx ,
Please confirm with v2.7.2 .
If still not fixed then attach the JPA Modeler file.

**Comment by neorevx** [comment]
It's fixed. :D
Thank you!
