### ISSUE TITLE
Default value for fields/columns

### ISSUE THREAD

**Issue by neorevx** [jGauravGupta/JPAModeler#83]
Hi,

I think a great enhancement is to add the default values ​​option to the fields / columns.
This property can be a direct code. In this way, we can use the composition of constants of other classes.
String may have the "literal" option, but I do not think it's required.

Ty

**Comment by jGauravGupta** [comment]
Please provide some example and sample code snippet.

Thanks and kind regards,
Gaurav Gupta
<https://twitter.com/intent/follow?original_referer=https%3A%2F%2Fabout.twitter.com%2Fresources%2Fbuttons&ref_src=twsrc%5Etfw&region=follow_link&screen_name=jpamodeler&tw_p=followbutton>
<http://jpamodeler.github.io/>   <https://www.youtube.com/JPAModeler>

**Comment by neorevx** [comment]
It's simple.

All fields/columns are generated like (Java initialize value as null or 0):

`private Permission permission;`

When I told 'default value', I just thought set initial value for field:

`private Permission permission = defaultValueComesHere;`

Example:

`private Permission permission = Permission.NONE;`

For this case, the property "Initial Value/Default Value" is set to `Permission.NONE`.

Set direct code it's usefull for expressions. Exemple `Permission.NONE.getCode()+10`

For strings the user must include quotation marks.

**Comment by neorevx** [comment]
It can be done with construtors (pre/pos code).
But when removing / adding fields, constructor must be updated, and it can be forgotten.

**Comment by jGauravGupta** [comment]
Yes, and it could also be done with *@Prepersist , *using new snippet
functionality*. *But here is also the same problem and it could be
forgotten to update for new/old/renamed fields.

BTW inline default value is good approach.

Thanks and kind regards,
Gaurav Gupta
<https://twitter.com/intent/follow?original_referer=https%3A%2F%2Fabout.twitter.com%2Fresources%2Fbuttons&ref_src=twsrc%5Etfw&region=follow_link&screen_name=jpamodeler&tw_p=followbutton>
<http://jpamodeler.github.io/>   <https://www.youtube.com/JPAModeler>

**Comment by jGauravGupta** [comment]
Fix : https://github.com/jGauravGupta/JPAModeler/releases/tag/2.6.7
