### ISSUE TITLE
Charset of generated code is different of charset of project

### ISSUE THREAD

**Issue by neorevx** [jGauravGupta/JPAModeler#84]
Hi,

I figured out that the charset of generated code by JPAModeler is different of default charset of my source code (UTF-8, set in project settings).

I included snippet with word "Saída" and the generated code is "Sa�da".

I can't find out what is the correct charset.

**Comment by jGauravGupta** [comment]
Fix : https://github.com/jGauravGupta/JPAModeler/releases/tag/2.6.7
