### ISSUE TITLE
Can't configure FetchType of Embeddable Collection in Entity

### ISSUE THREAD

**Issue by neorevx** [jGauravGupta/JPAModeler#86]
Hi,

Embeddable collections are generated as @ElementCollection field annoted.
Annotation @ElementCollection accept fetch parameter, but there's no way to configure that.
I think add this property is a good enhancement. But, I don't know if this parameter are take care by JPA.

p.s.: in last week I post few "Issues" here. It's because I'm loved your plugin and you made a great job. Thank you. If I have some time some day, I'll try create some functions for JPAModeler. :P

**Comment by jGauravGupta** [comment]
Thanks for reporting the issue
