### ISSUE TITLE
Feature Request: Universal UI Composer

### ISSUE THREAD

**Issue by Mobidat** [jGauravGupta/JPAModeler#89]
It would be awesome, to work with 3 Graphical Structures DB Modeler (is perfect realised), a JPA Modeler (also perfect) and the last and missing Structure is an UI Modeler, which is (prefered) adaptable to different UI Frameworks. I think a tree structure of Layout / Dialog Compenents would be ideal. 
I found a nice example with code generation for Vaadin classes here : 
http://jbossas-abitest.rhcloud.com/JaVaDe/ 
Referencing Views with existing Entities (JPA Modeler)  allow to generate Presenter- and DTO Classes fitting to the facade class generated from JPA Modeler.
How can I help to make this dream come true?

**Comment by jGauravGupta** [comment]
Hi @Mobidat,

For UI code generation, we have two strategy : 
1. Fixed template for UI (freemarker, velocity, ejs etc.)
2. UI designer


1. Angular JS client is developed using (1) EJS template. If you want to go with this strategy , please follow this tutorial to write any type of code generator : [http://jpamodeler.github.io/page.html?l=tutorial/Contribute](http://jpamodeler.github.io/page.html?l=tutorial/Contribute)

2. For UI designer (requires major effort) but you may check the following framework "jFluidon" and its implementation "Android designer" : , 
https://github.com/jGauravGupta/jFluidon , https://github.com/jGauravGupta/Android-Layout-Designer
** jFluidon is in-complete framework and it does not have any production implementation. 
** jFluidon is extended implementation of JavaFX Scene Builder.

UI designer is really awesome and fantastic until user does not have to change the source code of ui manually(after first time usage).
Real example : Google Android designer, JavaFx designer etc.
