### ISSUE TITLE
Named Queries

### ISSUE THREAD

**Issue by javydreamercsw** [jGauravGupta/JPAModeler#9]
It would be awesome if the default named queries were created as well like the default Netbeans system does them.

This might require so interfacing with NetBeans but I wouldn't see that as a big issue.

**Comment by jGauravGupta** [comment]
Thanks for the suggestion, 
In my view it would good , if JPA Modeler have some default named queries in panel (not in the source code),  developer just need to enable it , If they want to include in source code and they can also modify the query and add new query.

**Comment by jGauravGupta** [comment]
Please download v1.9 https://github.com/jGauravGupta/JPAModeler/releases/tag/1.9

Currently auto generation is only supported for @Basic with on rename refractor functionality.

@javydreamercsw  Please acknowledge for more enhancement and closer ;)

and If you don't mind, please fill out [http://jpamodeler.github.io/p/register_company.html](http://jpamodeler.github.io/p/register_company.html)

**Comment by javydreamercsw** [comment]
I just hoped it would use the existing ones within NetBeans instead of recreating the wheel.
