### ISSUE TITLE
Manage Entity Visibility is not showing all entities

### ISSUE THREAD

**Issue by neorevx** [jGauravGupta/JPAModeler#94]
Hi,

the window of "Manage Entity Visibility" is not showing all entities. I think that all entities are in list, but the list is cropped somehow.
The list os entities is not resizable, maybe is this.

Another thing: when I hide some entities, everytime I open the modeler it re-route. The modeler did not keep the old routes.

**Comment by jGauravGupta** [comment]
Can you please share the screen shot for issue "cropped".

The purpose of "Manage Entity Visibility" is to provide the compact visibility and usability to user . So it is re-rerouted to make user experience better in such case , if diagram have many entities and hidden entities create distance between visible entities so user have to scroll to view connectivity .

**Comment by neorevx** [comment]
![jpa](https://cloud.githubusercontent.com/assets/21008550/21063967/7d17d7a8-be3f-11e6-8d61-e6e89a932d47.png)

There is 1~4 entities I can't access in the list. These entities are below "CategoriaEstoque".

Re-route is a good thing, I know. But every time I open diagram with "invisible entities" it re-route, not only first time after manage entity visibility. If I open ten times the diagram file, ten times it'll re-route. Auto route has some random position, than when I open diagram, I don't know where is the entities anymore. I need to search.

**Comment by jGauravGupta** [comment]
These issues/requirement will be fixed in JPA diagram Workspace functionality : https://github.com/jGauravGupta/JPAModeler/issues/75

**Comment by neorevx** [comment]
Alright. Thank you.

**Comment by jGauravGupta** [comment]
Thanks for reporting the issue and prioritizing the task :)
