### ISSUE TITLE
Delete entity on Managed Entity Visibility may break diagram

### ISSUE THREAD

**Issue by neorevx** [jGauravGupta/JPAModeler#96]
HI,

Manage Entity Visibility is a good thing, but I think "delete" entity option should be disabled or warned if the entity has any relation with not visible entities.
The fields/columns and relations of an entity related with invisible entities are not shown. When delete entity with "invisible fields or relations" the diagram break. It's because some relations are not deleted properly.
I think the relations with invisible entities should be shown, but disabled.

Ty.

**Comment by neorevx** [comment]
Why?
I deleted an entity thinking it is empty (all fields are "invisible"). Then my diagram don't open again :(
I edited the jpa file and fixed de error copying some parts of an old diagram file (form Git). Now it's working again. :)

**Comment by jGauravGupta** [comment]
Hi @neorevx ,

**Manage Entity Visibility** functionality is developed in initial version of JPA Modeler. And in feature it will be replaced by Diagram Workspace functionality :  https://github.com/jGauravGupta/JPAModeler/issues/75
Which will be the enhanced version of current functionality.
